name: Test
on:
  push:
    branches:
      - main
jobs:
  start_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Server
        run: |
          go run spirozh/timr/cmd/server &
          sleep 10 # Wait for server to start
  check_response:
    runs-on: ubuntu-latest
    needs: start_server
    steps:
      - name: Install Hurl
        run: |
          VERSION=6.1.1
          sudo apt-add-repository -y ppa:lepapareil/hurl
          sudo apt install hurl="${VERSION}"*
      - uses: actions/checkout@v4
      - name: Hurl tests
        run: hurl --test test/hurl

