name: Test
on:
  push:
    branches:
      - main
jobs:
  env:
    SERVER_PORT: 8080
  http_server_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: start server
        run: make run &

      - name: run tests
        run: make test
